import 'package:vmodel/src/features/dashboard/discover/models/discover_item.dart';

List<DiscoverItemObject> recentlyViewed = [
  DiscoverItemObject('Samantha', 'assets/images/models/model_11.png', '4.9',
      'Face, Glamour, Food, Runway, Beauty'),
  DiscoverItemObject('Busayo', 'assets/images/models/model_11.png', '4.9',
      'Face, Glamour, Food, Runway, Beauty'),
  DiscoverItemObject('Busayo', 'assets/images/models/model_11.png', '4.9',
      'Face, Glamour, Food, Runway, Beauty'),
  DiscoverItemObject('Busayo', 'assets/images/models/model_11.png', '4.9',
      'Face, Glamour, Food, Runway, Beauty'),
  DiscoverItemObject('Busayo', 'assets/images/models/model_11.png', '4.9',
      'Face, Glamour, Food, Runway, Beauty'),
  DiscoverItemObject('Busayo', 'assets/images/models/model_11.png', '4.9',
      'Face, Glamour, Food, Runway, Beauty'),
  DiscoverItemObject('Busayo', 'assets/images/models/model_11.png', '4.9',
      'Face, Glamour, Food, Runway, Beauty'),
  DiscoverItemObject('Busayo', 'assets/images/models/model_11.png', '4.9',
      'Face, Glamour, Food, Runway, Beauty'),
  DiscoverItemObject('Busayo', 'assets/images/models/model_11.png', '4.9',
      'Face, Glamour, Food, Runway, Beauty'),
  DiscoverItemObject('Busayo', 'assets/images/models/model_11.png', '4.9',
      'Face, Glamour, Food, Runway, Beauty'),
  DiscoverItemObject('Busayo', 'assets/images/models/model_11.png', '4.9',
      'Face, Glamour, Food, Runway, Beauty'),
  DiscoverItemObject('Busayo', 'assets/images/models/model_11.png', '4.9',
      'Face, Glamour, Food, Runway, Beauty'),
  DiscoverItemObject('Busayo', 'assets/images/models/model_11.png', '4.9',
      'Face, Glamour, Food, Runway, Beauty'),
  DiscoverItemObject('Busayo', 'assets/images/models/model_11.png', '4.9',
      'Face, Glamour, Food, Runway, Beauty'),
  DiscoverItemObject('Busayo', 'assets/images/models/model_11.png', '4.9',
      'Face, Glamour, Food, Runway, Beauty'),
  DiscoverItemObject('Busayo', 'assets/images/models/model_11.png', '4.9',
      'Face, Glamour, Food, Runway, Beauty'),
  DiscoverItemObject('Busayo', 'assets/images/models/model_11.png', '4.9',
      'Face, Glamour, Food, Runway, Beauty'),
  DiscoverItemObject('Busayo', 'assets/images/models/model_11.png', '4.9',
      'Face, Glamour, Food, Runway, Beauty'),
];

List<DiscoverItemObject> mostPopular = [
  DiscoverItemObject('Rachael', 'assets/images/models/model_13.png', '4.9',
      'Face, Glamour, Food, Runway, Beauty'),
  DiscoverItemObject('James', 'assets/images/models/model_12.png', '4.9',
      'Face, Glamour, Food, Runway, Beauty'),
  DiscoverItemObject('Rachael', 'assets/images/models/model_13.png', '4.9',
      'Face, Glamour, Food, Runway, Beauty'),
  DiscoverItemObject('James', 'assets/images/models/model_12.png', '4.9',
      'Face, Glamour, Food, Runway, Beauty'),
  DiscoverItemObject('Busayo', 'assets/images/models/model_14.png', '4.9',
      'Face, Glamour, Food, Runway, Beauty'),
  DiscoverItemObject('Busayo', 'assets/images/models/model_14.png', '4.9',
      'Face, Glamour, Food, Runway, Beauty'),
  DiscoverItemObject('Rachael', 'assets/images/models/model_13.png', '4.9',
      'Face, Glamour, Food, Runway, Beauty'),
  DiscoverItemObject('James', 'assets/images/models/model_12.png', '4.9',
      'Face, Glamour, Food, Runway, Beauty'),
  DiscoverItemObject('Rachael', 'assets/images/models/model_13.png', '4.9',
      'Face, Glamour, Food, Runway, Beauty'),
  DiscoverItemObject('James', 'assets/images/models/model_12.png', '4.9',
      'Face, Glamour, Food, Runway, Beauty'),
  DiscoverItemObject('Busayo', 'assets/images/models/model_14.png', '4.9',
      'Face, Glamour, Food, Runway, Beauty'),
  DiscoverItemObject('Rachael', 'assets/images/models/model_13.png', '4.9',
      'Face, Glamour, Food, Runway, Beauty'),
  DiscoverItemObject('James', 'assets/images/models/model_12.png', '4.9',
      'Face, Glamour, Food, Runway, Beauty'),
  DiscoverItemObject('Busayo', 'assets/images/models/model_14.png', '4.9',
      'Face, Glamour, Food, Runway, Beauty'),
  DiscoverItemObject('Busayo', 'assets/images/models/model_14.png', '4.9',
      'Face, Glamour, Food, Runway, Beauty'),
  DiscoverItemObject('Rachael', 'assets/images/models/model_13.png', '4.9',
      'Face, Glamour, Food, Runway, Beauty'),
  DiscoverItemObject('James', 'assets/images/models/model_12.png', '4.9',
      'Face, Glamour, Food, Runway, Beauty'),
  DiscoverItemObject('Busayo', 'assets/images/models/model_14.png', '4.9',
      'Face, Glamour, Food, Runway, Beauty'),
];

List<DiscoverItemObject> locals = [
  DiscoverItemObject('Natalie', 'assets/images/models/model_16.png', '4.9',
      'Face, Glamour, Food, Runway, Beauty'),
  DiscoverItemObject('Rachael', 'assets/images/models/model_15.png', '4.9',
      'Face, Glamour, Food, Runway, Beauty'),
  DiscoverItemObject('Natalie', 'assets/images/models/model_16.png', '4.9',
      'Face, Glamour, Food, Runway, Beauty'),
  DiscoverItemObject('Rachael', 'assets/images/models/model_15.png', '4.9',
      'Face, Glamour, Food, Runway, Beauty'),
  DiscoverItemObject('Busayo', 'assets/images/models/model_11.png', '4.9',
      'Face, Glamour, Food, Runway, Beauty'),
  DiscoverItemObject('Natalie', 'assets/images/models/model_16.png', '4.9',
      'Face, Glamour, Food, Runway, Beauty'),
  DiscoverItemObject('Rachael', 'assets/images/models/model_15.png', '4.9',
      'Face, Glamour, Food, Runway, Beauty'),
  DiscoverItemObject('Busayo', 'assets/images/models/model_11.png', '4.9',
      'Face, Glamour, Food, Runway, Beauty'),
  DiscoverItemObject('Busayo', 'assets/images/models/model_11.png', '4.9',
      'Face, Glamour, Food, Runway, Beauty'),
  DiscoverItemObject('Natalie', 'assets/images/models/model_16.png', '4.9',
      'Face, Glamour, Food, Runway, Beauty'),
  DiscoverItemObject('Rachael', 'assets/images/models/model_15.png', '4.9',
      'Face, Glamour, Food, Runway, Beauty'),
  DiscoverItemObject('Busayo', 'assets/images/models/model_11.png', '4.9',
      'Face, Glamour, Food, Runway, Beauty'),
  DiscoverItemObject('Busayo', 'assets/images/models/model_11.png', '4.9',
      'Face, Glamour, Food, Runway, Beauty'),
  DiscoverItemObject('Busayo', 'assets/images/models/model_11.png', '4.9',
      'Face, Glamour, Food, Runway, Beauty'),
  DiscoverItemObject('Natalie', 'assets/images/models/model_16.png', '4.9',
      'Face, Glamour, Food, Runway, Beauty'),
  DiscoverItemObject('Rachael', 'assets/images/models/model_15.png', '4.9',
      'Face, Glamour, Food, Runway, Beauty'),
  DiscoverItemObject('Busayo', 'assets/images/models/model_11.png', '4.9',
      'Face, Glamour, Food, Runway, Beauty'),
  DiscoverItemObject('Rachael', 'assets/images/models/model_15.png', '4.9',
      'Face, Glamour, Food, Runway, Beauty'),
];

List<DiscoverItemObject> petModels = [
  DiscoverItemObject('Rachael', 'assets/images/pets/pet_2.png', '4.9',
      'Face, Glamour, Food, Runway, Beauty'),
  DiscoverItemObject('Natalie', 'assets/images/models/model_11.png', '4.9',
      'Face, Glamour, Food, Runway, Beauty'),
  DiscoverItemObject('Busayo', 'assets/images/models/model_11.png', '4.9',
      'Face, Glamour, Food, Runway, Beauty'),
];

List<DiscoverItemObject> photoModels = [
  DiscoverItemObject(
      'Rachael',
      'assets/images/photographers/photographer_7.png',
      '4.9',
      'Face, Glamour, Food, Runway, Beauty'),
  DiscoverItemObject(
      'Natalie',
      'assets/images/photographers/photographer_1.png',
      '4.9',
      'Face, Glamour, Food, Runway, Beauty'),
  DiscoverItemObject('Busayo', 'assets/images/photographers/photographer_2.png',
      '4.9', 'Face, Glamour, Food, Runway, Beauty'),
];

List<DiscoverItemObject> contentModels = [
  DiscoverItemObject('Rachael', 'assets/images/models/model_11.png', '4.9',
      'Face, Glamour, Food, Runway, Beauty'),
  DiscoverItemObject('Natalie', 'assets/images/models/model_12.png', '4.9',
      'Face, Glamour, Food, Runway, Beauty'),
  DiscoverItemObject('Busayo', 'assets/images/models/model_13.png', '4.9',
      'Face, Glamour, Food, Runway, Beauty'),
];

List<String> categories = ['Models', 'Creators', 'Photographers', 'pets'];
List<String> tags = [
  'Lingerie',
  'Glamour',
  'Parts',
  'Editorial',
  'Commercial',
  'Campaigns'
];

List<String> imagesAsset = [
  'assets/images/doc/main-model.png',
  'assets/images/models/model_3.png',
  'assets/images/models/model_11.png',
  'assets/images/models/model_12.png',
  'assets/images/models/model_13.png',
  'assets/images/models/model_14.png',
  'assets/images/models/model_2.png',
  'assets/images/models/model_2.png',
];
